### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by ramonsaraiva** [FarhadurFahim/movie_finder#1]
Hey, i've followed your instructions and they does not work :(

```
➜  ~ scrapy crawl finder -o /tmp/output.csv
Scrapy 1.3.3 - no active project

Unknown command: crawl

Use "scrapy" to see available commands
```

**Comment by rezafarhadur** [comment]
May be your current directory isn't this project directory. Make sure you are in project root directory. 

>From your command it shows you are not in project directory.

After clone or download this [repo](https://github.com/FarhadurFahim/movie_finder) goto project directory and run `scrapy crawl finder -o output.csv` on terminal. Don't forget to install **scrapy**.

For details follow their [documentation](https://doc.scrapy.org/en/latest/intro/tutorial.html#our-first-spider).

Hope it will works now.

**Comment by ramonsaraiva** [comment]
Oh, so i totally misunderstood.
I thought that i was `pip`in your project itself, and not just a package that is needed by it, sorry :-)

Will try it later, thanks.
